name: Build libemoji

runs:
  using: composite
  steps:
    - name: Show CMake version
      run: cmake --version
      shell: bash
    - name: Show Python version
      run: python --version
      shell: bash

