name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  python-versions:
    runs-on: ubuntu-latest
    name: Collect Python versions
    outputs:
      value: ${{ steps.run-script.outputs.python-versions }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/collect-python-versions
        id: run-script
  prebuild:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: Prebuild (${{ matrix.os }})
    outputs:
      artifact-name: ${{ steps.prebuild.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Prebuild
        uses: ./.github/actions/prebuild
        id: prebuild
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version: ${{ fromJson(needs.python-versions.outputs.value) }}
    needs: [ prebuild, python-versions ]
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/build
        with:
          python-version: ${{ matrix.python-version }}
          artifact-name: ${{ needs.prebuild.outputs.artifact-name }}
