name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  build_libemoji:
    strategy:
      matrix:
        os:
          - macos-latest
          # - ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: Build libemoji (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libfontconfig1-dev libx11-dev \
            libxcomposite-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev
      - name: Show CMake version
        run: cmake --version
      - name: Show Python version
        run: python --version
      - name: Build libemoji
        run: |
          cd externals/libemoji
          cmake .
          cmake --build .
          du -h tmp/libskia.a
          du -h lib/libemoji.a
      - name: Upload libemoji.a
        uses: actions/upload-artifact@v7
        with:
          name: libemoji_${{ matrix.os }}
          path: externals/libemoji/lib/libemoji.a
  test_emojilib:
    strategy:
      matrix:
        os:
          - macos-latest
          # - ubuntu-latest
        python-version:
          # - '3.13'
          - '3.14'
    needs: [ build_libemoji ]
    runs-on: ${{ matrix.os }}
    name: Test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Show Python version
        run: python --version
      - name: Download libemoji.a
        uses: actions/download-artifact@v8
        with:
          name: libemoji_${{ matrix.os }}
