name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  prebuild:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    name: Prebuild (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libfontconfig1-dev libx11-dev \
            libxcomposite-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev
      - name: Show CMake version
        run: cmake --version
      - name: Show Python version
        run: python --version
      - name: Build libemoji
        run: |
          cd externals/libemoji
          cmake .
          cmake --build .
          du -h tmp/libskia.a
          du -h lib/libemoji.a
      - name: Upload libemoji.a
        uses: actions/upload-artifact@v7
        with:
          name: lib-${{ matrix.os }}
          path: externals/libemoji/lib/libemoji.a
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        python-version:
          - '3.13'
          - '3.14'
    needs: [ prebuild ]
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os }}, py${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libfontconfig1-dev libx11-dev \
            libxcomposite-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: arm64
      - name: Show Python version
        run: python --version
      - name: Download libemoji.a
        uses: actions/download-artifact@v8
        with:
          name: lib-${{ matrix.os }}
          path: externals/libemoji/lib
      - name: Check artifact
        run: |
          ls -R lib
          file lib/libemoji.a
          du -h lib/libemoji.a
      - name: Test
        env:
          ARCHFLAGS: ''
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build pytest wheel Cython
          python -m build --wheel
          python -m pip install .
          python -m pytest test

